import numpy as np
#########################################
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)
toplama=a+5
cikarma=a-5
bolme=a/4
carpma=a*2
kalan=a%2
üst_alma=a**2
print(toplama)
print(cikarma)
print(bolme)
print(carpma)
print(kalan)
print(üst_alma)
##########################################
#ufunc lar ile de yaparsak
toplama2=np.add(a,1)
cikarma2=np.subtract(a,1)
bolme2=np.divide(a,2)
carpma2=np.multiply(a,2)
kalan2=np.mod(a,3)
üst_alma2=np.power(a,2)
print(toplama2)
print(cikarma2)
print(bolme2)
print(carpma2)
print(kalan2)
print(üst_alma2)
mutlak=np.absolute(np.array([-9]))
print(mutlak)
sinus=np.sin(360)
print(sinus)
cosinus=np.cos(360)
print(cosinus)
logaritma=np.log(a)
log_2=np.log2(a)
print(logaritma)
print(log_2)
b=np.array([10,11,12,13,14,15,16,17,18]).reshape(3,3)
c=np.multiply(a,b)
print(c)